### ISSUE TITLE
Variable syntax recognition

### ISSUE THREAD

**Issue by Angelk90** [zarifpour/zed-env#1]
Hi! @zarifpour , here is an example file:

```env
# Interpolated string with shell commands
DATABASE_URL="postgres://$(whoami)@localhost/my_database"

# Interpolated string with other env var
DATABASE_URL="postgres://$USER@localhost/my_database"

# Interpolated string with other env var, with braces
DATABASE_URL="postgres://${USER}@localhost/my_database"

# Interpolated string with other env var, with default value
DATABASE_URL="postgres://${USER:-default}@localhost/my_database"

INTERPOLATED_VAR=I have a ${SIMPLE_VAR}

CURRENT_DATE=$(date +%Y-%m-%d)
``` 

Vscode:

<img width="517" alt="Screenshot 2024-07-12 alle 17 18 34" src="https://github.com/user-attachments/assets/a02d02ad-dbdc-4e35-8caa-65acb205d4ed">

**Comment by zarifpour** [comment]
how does this look to you?

![CleanShot_2024-07-12_17 09 01_Zed_001416@2x](https://github.com/user-attachments/assets/e608a3c7-4c96-4884-b393-07113209c131)

**Comment by zarifpour** [comment]
Feel free to reopen if you disagree.

**Comment by Angelk90** [comment]
@zarifpour : I congratulate you, here are some considerations, from the images I think you can understand the differences.

Zed:

<img width="507" alt="Screenshot 2024-07-13 alle 08 36 20" src="https://github.com/user-attachments/assets/781ea4ef-c240-4bba-8557-2c2cc350b771">

Vscode:

<img width="515" alt="Screenshot 2024-07-13 alle 08 36 10" src="https://github.com/user-attachments/assets/0900d6a4-cee8-4bf4-8058-95f21385823f">

Code:

```env
DATABASE_URL="postgres://$(whoami)@localhost/my_database"
DATABASE_URL="postgres://$USER@localhost/my_database"
DATABASE_URL="postgres://${USER}@localhost/my_database"
DATABASE_URL="postgres://${USER:-default}@localhost/my_database"

DATABASE_URL=postgres://$(whoami)@localhost/my_database
DATABASE_URL=postgres://$USER@localhost/my_database
DATABASE_URL=postgres://${USER}@localhost/my_database
DATABASE_URL=postgres://${USER:-default}@localhost/my_database

DATABASE_URL='postgres://$(whoami)@localhost/my_database'
DATABASE_URL='postgres://$USER@localhost/my_database'
DATABASE_URL='postgres://${USER}@localhost/my_database'
DATABASE_URL='postgres://${USER:-default}@localhost/my_database'

INTERPOLATED_VAR=I have a ${SIMPLE_VAR}
CURRENT_DATE=$(date +%Y-%m-%d)
db-uri="postgres://postgres@localhost/zed"
server-port=8081
jwt-secret="the-postgrest-jwt-secret-for-authorization"
log-level="info"
db-url="postgres://${USER:-default}@localhost/my_database"
test-one=true
```

**Comment by zarifpour** [comment]
@Angelk90 it's probably your theme. Try it with [XY-Zed](https://github.com/zarifpour/xy-zed)

**Comment by Angelk90** [comment]
@zarifpour : I don't think anything changes.
<img width="510" alt="Screenshot 2024-07-14 alle 09 50 59" src="https://github.com/user-attachments/assets/fe07fc36-7140-48d4-95ef-9f72282b9292">
